import os
from typing import Dict, Any, List
from agent.models.task_spec import TaskSpec
from agent.models.architecture_plan import ArchitecturePlan

class DocumentationBuilder:
    """
    Phase 9 Module: Generates comprehensive README.md, API_DOCS.md, and ARCHITECTURE.md.
    """

    def generate_documentation(self, spec: TaskSpec, plan: ArchitecturePlan, project_dir: str) -> Dict[str, str]:
        """
        Generates markdown documentation files and writes them to project_dir.
        """
        docs = {}

        # 1. README.md
        docs["README.md"] = self._build_readme(spec, plan)

        # 2. API_DOCS.md
        docs["API_DOCS.md"] = self._build_api_docs(spec)

        # 3. ARCHITECTURE.md
        docs["ARCHITECTURE.md"] = self._build_architecture_doc(spec, plan)

        # Write to disk
        for filename, content in docs.items():
            file_path = os.path.join(project_dir, filename)
            with open(file_path, "w", encoding="utf-8") as f:
                f.write(content)

        return docs

    def _build_readme(self, spec: TaskSpec, plan: ArchitecturePlan) -> str:
        features_list = "\n".join([f"- ✅ {f}" for f in spec.requested_features])
        env_vars_table = "| Variable | Description | Default |\n| --- | --- | --- |\n"
        for k, v in spec.environment_variables.items():
            env_vars_table += f"| `{k}` | Environment variable for service | `{v}` |\n"

        return f"""# 🚀 {spec.project_name.replace('_', ' ').title()}

> {spec.description}

---

## ✨ Features
{features_list}

---

## 🛠 Tech Stack
- **Primary Language**: `{spec.primary_language.upper()}`
- **Framework**: `{spec.framework or 'FastAPI'}`
- **Database**: `{spec.database or 'SQLite'}`

---

## ⚙️ Quick Setup & Execution

### 1. Prerequisites
- Python 3.10+ or Node.js v18+

### 2. Installation
```bash
# Clone the repository
git clone <repository-url>
cd {spec.project_name}

# Install dependencies
pip install -r requirements.txt
```

### 3. Running the Server
```bash
python main.py
```
Server will be active at: `http://localhost:8000`

---

## 🔐 Environment Variables
{env_vars_table}

---

## 📖 API Documentation
Detailed API endpoints reference can be found in [`API_DOCS.md`](./API_DOCS.md).

---

## 🏗 System Architecture
Detailed module breakdown and database ER diagram can be found in [`ARCHITECTURE.md`](./ARCHITECTURE.md).
"""

    def _build_api_docs(self, spec: TaskSpec) -> str:
        rows = "| Method | Endpoint Path | Description |\n| --- | --- | --- |\n"
        for ep in spec.api_endpoints:
            rows += f"| `{ep['method']}` | `{ep['path']}` | {ep['description']} |\n"

        return f"""# 📖 API Documentation — {spec.project_name.title()}

Below is the complete REST API specification auto-generated by the Autonomous Coding Agent.

---

## 🚀 Endpoints Summary

{rows}

---

## 💡 Example Request & Response

### GET `/health`
**Response (200 OK):**
```json
{{
  "status": "healthy",
  "service": "{spec.project_name}"
}}
```

### POST `/api/v1/items`
**Request Body:**
```json
{{
  "name": "Sample Item",
  "detail": "Detailed description",
  "status": "active"
}}
```

**Response (200 OK):**
```json
{{
  "id": 1,
  "name": "Sample Item",
  "detail": "Detailed description",
  "status": "active"
}}
```
"""

    def _build_architecture_doc(self, spec: TaskSpec, plan: ArchitecturePlan) -> str:
        modules_str = "\n".join([f"- **{m['name']}**: {m['description']}" for m in plan.modules])
        
        tables_str = ""
        for t in plan.db_schema.get("tables", []):
            tables_str += f"### Table: `{t['table_name']}`\n```sql\n{t['ddl']}\n```\n\n"

        return f"""# 🏗 Architecture & Design Specification

---

## 📦 System Modules
{modules_str}

---

## 🗄 Database Schema (DDL)
{tables_str}

---

## 🔄 Execution Flow
```
Client Request ---> API Router ---> Service / Business Logic ---> Database ORM ---> SQLite / MySQL
```
"""
